version: '3.1'

services:
  ecommerce_pg:
    image: postgres:15.1-alpine
    container_name: ecommerce_pg
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: uecommerce
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432